name: test-all

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 21 * * Tue'

jobs:
  test_php82_mysql8_mongo4_redis5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo4_redis5.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec yii2-base-models-php82_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec yii2-base-models-php82_php_1 sh -c "XDEBUG_MODE=coverage phpunit"
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo4_redis5.yml down
  test_php82_mysql8_mongo4_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo4_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec yii2-base-models-php82_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec yii2-base-models-php82_php_1 sh -c "XDEBUG_MODE=coverage phpunit"
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo4_redis6.yml down
  test_php82_mysql8_mongo5_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo5_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec yii2-base-models-php82_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec yii2-base-models-php82_php_1 sh -c "XDEBUG_MODE=coverage phpunit"
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo5_redis6.yml down
  test_php82_mysql8_mongo5_redis7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo5_redis7.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec yii2-base-models-php82_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec yii2-base-models-php82_php_1 sh -c "XDEBUG_MODE=coverage phpunit"
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo5_redis7.yml down
  test_php82_mysql8_mongo6_redis7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo6_redis7.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec yii2-base-models-php82_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec yii2-base-models-php82_php_1 sh -c "XDEBUG_MODE=coverage phpunit"
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/yii2-base-models-php82/php82_mysql8_mongo6_redis7.yml down
