name: test

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 21 * * Tue'

jobs:
  test_php73_mysql8_mongo4_redis5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php73_mysql8_mongo4_redis5.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php73_mysql8_mongo4_redis5.yml down
  test_php73_mysql8_mongo4_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php73_mysql8_mongo4_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php73_mysql8_mongo4_redis6.yml down
  test_php73_mysql8_mongo5_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php73_mysql8_mongo5_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php73_mysql8_mongo5_redis6.yml down
  test_php74_mysql8_mongo4_redis5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php74_mysql8_mongo4_redis5.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php74_mysql8_mongo4_redis5.yml down
  test_php74_mysql8_mongo4_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php74_mysql8_mongo4_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php74_mysql8_mongo4_redis6.yml down
  test_php74_mysql8_mongo5_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php74_mysql8_mongo5_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php74_mysql8_mongo5_redis6.yml down
  test_php80_mysql8_mongo4_redis5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php80_mysql8_mongo4_redis5.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php80_mysql8_mongo4_redis5.yml down
  test_php80_mysql8_mongo4_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php80_mysql8_mongo4_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php80_mysql8_mongo4_redis6.yml down
  test_php80_mysql8_mongo5_redis6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f tests/environments/php80_mysql8_mongo5_redis6.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec environments_php_1 sh -c "composer install && composer require yiisoft/yii2-mongodb yiisoft/yii2-redis"
          sleep 60
      - name: Run tests
        run: docker exec environments_php_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/php80_mysql8_mongo5_redis6.yml down
